image: condaforge/linux-anvil:latest

variables:
  PKG_NAME: "pdb2pqr"
  CONDA_ROOT_DIR: "/opt/conda"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - conda config --append channels kimlab
    - cd $CI_PROJECT_DIR/devtools/conda-recipe
    - conda build .
    # Save conda package
    - cd $CI_PROJECT_DIR
    - mkdir ./conda-bld
    - cp -r $CONDA_ROOT_DIR/conda-bld/{linux-64,noarch} ./conda-bld
  artifacts:
    paths:
    - conda-bld

.test_template: &test_definition  # Hidden key that defines an anchor named 'job_definition'
  stage: test
  script:
    - conda config --append channels kimlab
    - cp -r ./conda-bld/* $CONDA_ROOT_DIR/conda-bld/
    - conda index $CONDA_ROOT_DIR/conda-bld/
    - conda install 'requests<2.12'
    - conda install -yq --use-local $PKG_NAME
    # Custom
    - conda env remove -n scons -y || true
    - conda create -fyq -n scons python scons openssl readline ncurses
    - cd pdb2pqr
    - export PYTHON=$(which python)
    - $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py $TEST_NAME

test_local-test:
  variables:
    TEST_NAME: "local-test"
  <<: *test_definition

test_basic-test:
  variables:
    TEST_NAME: "basic-test"
  <<: *test_definition

test_pdb2pka-test:
  variables:
    TEST_NAME: "pdb2pka-test"
  <<: *test_definition

test_advanced-test:
  variables:
    TEST_NAME: "advanced-test"
  <<: *test_definition

deploy:
  stage: deploy
  script:
    - anaconda -t $ANACONDA_TOKEN upload `pwd`/conda-bld/linux-64/*.tar.bz2 -u kimlab
  only:
    - master
