image: condaforge/linux-anvil:latest

variables:
  PKG_NAME: "pdb2pqr"
  CONDA_ROOT_DIR: "/opt/conda"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - conda config --append channels kimlab
    - cd $CI_PROJECT_DIR/devtools/conda-recipe
    - conda build .
    # Save conda package
    - cd $CI_PROJECT_DIR
    - mkdir ./conda-bld
    - cp -r $CONDA_ROOT_DIR/conda-bld/{linux-64,noarch} ./conda-bld
  artifacts:
    paths:
    - conda-bld

.test_template: &test_job
  stage: test
  before_script:
    - conda config --append channels kimlab
    - cp -r ./conda-bld/* $CONDA_ROOT_DIR/conda-bld/
    - conda index $CONDA_ROOT_DIR/conda-bld/
    - conda install 'requests<2.12'
    - conda install -yq --use-local $PKG_NAME
    # Custom
    - conda env remove -n scons -y || true
    - conda create -fyq -n scons python scons openssl readline ncurses
    - cd pdb2pqr
    - export PYTHON=$(which python)

# Basic tests
basic-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "basic-test"

local-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "local-test"

advanced-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "advanced-test"

# Complicated tests
long-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "long-test"

complete-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "complete-test"

pdb2pka-test:
  <<: *test_job
  script:
    $CONDA_ROOT_DIR/envs/scons/bin/scons scons/scons.py "pdb2pka-test"

#
deploy:
  stage: deploy
  script:
    - anaconda -t $ANACONDA_TOKEN upload `pwd`/conda-bld/linux-64/*.tar.bz2 -u kimlab
  only:
    - master
