package:
  name: pdb2pqr
  version: "2.1.2a1"

source:
  path: ..


build:
  number: 1
  script: python setup.py install

test:
    files:
        - 3PTB.pdb
    commands:
        - pdb2pqr_cli --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr


requirements:
  build:
    - python  >=3.5
    - setuptools
  run:
    - python >=3.5
    - propka

about:
  home: http://www.poissonboltzmann.org/
  license: "BSD"
