package:
  name:  pdb2pqr
  version: 1.5

build:
  number: 0

source:
  path: ../../

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - networkx
    - propka
    - pdb2pka
    - future

test:
  files:
    - 3PTB.pdb
  source_files:
    - pdb2pqr/scons/**
    - pdb2pqr/site_scons/**
    - pdb2pqr/tests/**
    - pdb2pqr/SConstruct
    - pdb2pqr/SConscript*
  commands:
    - pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 3PTB.pdb 3PTB.pqr
    - pdb2pqr_cli --verbose --ff parse --with-ph=7.0 --ff=parse --ph-calc-method=propka31 pdb2pqr/tests/local-test/1AFS.pdb 1AFS.pqr

about:
  home: http://www.poissonboltzmann.org/
  license: "BSD"
